# Generated by Django 3.0.7 on 2020-06-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vault',
            new_name='Item',
        ),
    ]
